apiVersion : apps/v1
kind: Deployment
metadata:
  name: mycicd 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycicd
  template:
    metadata:
      labels:
        app: mycicd
    spec:
      containers:
        - name: mycicd 
          image: osygroup/craze:83
          ports:
          - containerPort: 80




---

apiVersion: v1
kind: Service
metadata:
    name: mycicd
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: mycicd
