
name: "Deploy app to my AKS cluster"
on:
  push:
    # run on pushes to master
    branches:
      - master
jobs:
  push-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/simplewhale:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account set --subscription 11a3de11-9814-4ebd-8c31-3665a9ef4bfa
          az aks get-credentials --resource-group eshop-learn-rg --name eshop-learn-aks

    - uses: azure/setup-kubectl@v1
    - name: kubectl deploy to cluster
      run: |
        kubectl apply -f deployment.yaml -n boutique-app
